---
- name: Assignment 2
  hosts: web

  tasks:
    - name: install git
      yum:
        name: git
        state: installed
    - name: install wget
      yum:
        name: wget
        state: installed
...
